# Generated by Django 2.2.1 on 2019-06-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='people/img/', verbose_name='image'),
        ),
    ]
